In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("heart_data.csv")

In [24]:
df.head()

age  sex   BP  cholestrol  heart disease
0   70    1  130         322              1
1   67    0  115         564              0
2   57    1  124         261              1
3   64    1  128         263              0
4   74    0  120         269              0

In [25]:
df.isnull().sum()

age              0
sex              0
BP               0
cholestrol       0
heart disease    0
dtype: int64

In [26]:
# feature scalling - standization,normalization

In [27]:
#linerar, logics = standization

In [28]:
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()

In [29]:
x = df.drop(columns=["heart disease"])
y = df["heart disease"]

In [30]:
x.head()

age  sex   BP  cholestrol
0   70    1  130         322
1   67    0  115         564
2   57    1  124         261
3   64    1  128         263
4   74    0  120         269

In [31]:
y

0      1
1      0
2      1
3      0
4      0
      ..
265    0
266    0
267    0
268    0
269    1
Name: heart disease, Length: 270, dtype: int64

In [32]:
#split data into 80% and 20%. After spliting the data
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42) 

In [33]:
# we scale only independent varaiable
x_train_scaled = sd.fit_transform(x_train)
x_test_scaled = sd.transform(x_test)

In [34]:
x_test_scaled

array([[ 2.45561820e-01,  6.56097231e-01, -2.11259717e-01,
        -4.12347574e-01],
       [-9.62419307e-01,  6.56097231e-01, -6.59732432e-01,
        -2.24719952e-02],
       [ 1.35745354e-01,  6.56097231e-01, -6.59732432e-01,
        -2.75891121e-01],
       [-3.03520510e-01, -1.52416434e+00,  2.37212999e-01,
        -1.05564228e+00],
       [ 3.55378286e-01, -1.52416434e+00, -1.78091422e+00,
        -4.19657741e-02],
       [ 1.35745354e-01,  6.56097231e-01, -3.79436985e-01,
        -2.24719952e-02],
       [-1.95076750e+00,  6.56097231e-01, -9.91415378e-02,
        -2.97821623e-03],
       [ 3.55378286e-01,  6.56097231e-01,  4.61449357e-01,
        -7.63235594e-01],
       [ 1.35745354e-01,  6.56097231e-01, -6.59732432e-01,
        -1.11412362e+00],
       [ 1.12409355e+00, -1.52416434e+00,  1.30233570e+00,
         3.67403583e-01],
       [-1.40168517e+00, -1.52416434e+00, -1.66879604e+00,
         2.89428468e-01],
       [ 2.45561820e-01,  6.56097231e-01,  4.61449357e-01,
      

In [35]:
new_x_train = pd.DataFrame(x_train_scaled,columns=x.columns)

In [36]:
x_test_scaled

array([[ 2.45561820e-01,  6.56097231e-01, -2.11259717e-01,
        -4.12347574e-01],
       [-9.62419307e-01,  6.56097231e-01, -6.59732432e-01,
        -2.24719952e-02],
       [ 1.35745354e-01,  6.56097231e-01, -6.59732432e-01,
        -2.75891121e-01],
       [-3.03520510e-01, -1.52416434e+00,  2.37212999e-01,
        -1.05564228e+00],
       [ 3.55378286e-01, -1.52416434e+00, -1.78091422e+00,
        -4.19657741e-02],
       [ 1.35745354e-01,  6.56097231e-01, -3.79436985e-01,
        -2.24719952e-02],
       [-1.95076750e+00,  6.56097231e-01, -9.91415378e-02,
        -2.97821623e-03],
       [ 3.55378286e-01,  6.56097231e-01,  4.61449357e-01,
        -7.63235594e-01],
       [ 1.35745354e-01,  6.56097231e-01, -6.59732432e-01,
        -1.11412362e+00],
       [ 1.12409355e+00, -1.52416434e+00,  1.30233570e+00,
         3.67403583e-01],
       [-1.40168517e+00, -1.52416434e+00, -1.66879604e+00,
         2.89428468e-01],
       [ 2.45561820e-01,  6.56097231e-01,  4.61449357e-01,
      

In [37]:
new_x_test = pd.DataFrame(x_test_scaled,columns=x.columns)

In [38]:
# training,testing
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [39]:
lr.fit(new_x_train,y_train)

LogisticRegression()

In [40]:
#prediction
y_pred = lr.predict(new_x_train)

In [49]:
# test the data, by using X_test - new_x_test
y_pred = lr.predict(new_x_test)
y_pred

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [50]:
print(confusion_matrix(y_test,y_pred))
print("The accureacy is :", accuracy_score(y_test,y_pred))
print("The precision is :",precision_score(y_test,y_pred))
print("The recall is :",recall_score(y_test,y_pred))
print("The f1 is :",f1_score(y_test,y_pred)) 

[[26  7]
 [10 11]]
The accureacy is : 0.6851851851851852
The precision is : 0.6111111111111112
The recall is : 0.5238095238095238
The f1 is : 0.5641025641025641


In [51]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [52]:
knn.fit(new_x_train,y_train)

KNeighborsClassifier()

In [53]:
y_pred1 = knn.predict(new_x_train)
y_pred1

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0])

In [58]:
print(confusion_matrix(y_test,y_pred1))
print("The accureacy is :", accuracy_score(y_test,y_pred1))
print("The precision is :",precision_score(y_test,y_pred1))
print("The recall is :",recall_score(y_test,y_pred1))
print("The f1 is :",f1_score(y_test,y_pred1)) 

[[ 0 33]
 [ 0 21]]
The accureacy is : 0.3888888888888889
The precision is : 0.3888888888888889
The recall is : 1.0
The f1 is : 0.56


In [59]:
print(accuracy_score(y_test,y_pred1))

0.3888888888888889


In [60]:
#implementing Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [61]:
#Training data
dt.fit(new_x_train, y_train)

DecisionTreeClassifier()

In [63]:
y_pred2 = dt.predict(new_x_train)

In [88]:
print("y_test shape:", y_test.shape)
print("y_pred2 shape:", y_pred2.shape)
print("y_test type:", type(y_test))
print("y_pred2 type:", type(y_pred2))

y_test shape: (54,)
y_pred2 shape: (54,)
y_test type: <class 'pandas.core.series.Series'>
y_pred2 type: <class 'numpy.ndarray'>


In [85]:
import numpy as np

# Replicate y_test to match the size of y_pred2
y_test_expanded = np.tile(y_test, 4)[:216]  # Repeat 4 times and truncate to 216

print("New y_test shape:", y_test_expanded.shape)

# Check if the shapes now match
if y_test_expanded.shape == y_pred2.shape:
    print("Confusion Matrix:")
    print(confusion_matrix(y_test_expanded, y_pred2))
else:
    print("Error: Shapes still don't match.")

New y_test shape: (216,)
Error: Shapes still don't match.


In [87]:
y_pred2_subsampled = y_pred2[:54]  # Take the first 54 predictions

# Check if the shapes now match
if y_test.shape == y_pred2_subsampled.shape:
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred2_subsampled))
else:
    print("Error: Shapes still don't match.")

Confusion Matrix:
[[ 0 33]
 [ 0 21]]


In [89]:
print(confusion_matrix(y_test,y_pred2))
print(accuracy_score(y_test,y_pred2))
print(precision_score(y_test,y_pred2))
print(recall_score(y_test,y_pred2))
print(f1_score(y_test,y_pred2))

[[ 0 33]
 [ 0 21]]
0.3888888888888889
0.3888888888888889
1.0
0.56


In [41]:
import joblib 
joblib.dump(lr,'logistic.pkl')

['logistic.pkl']

In [42]:
pip install streamlit

Note: you may need to restart the kernel to use updated packages.


In [43]:
pip install mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


In [44]:
pip install streamlit mysql-connector-python

Note: you may need to restart the kernel to use updated packages.


In [45]:
import mysql.connector
def connect_to_db():
    return mysql.connector.connect(
        host="localhost",
        user="root",  # Change this
        password="root",  # Change this
        database="heart_data")

In [46]:
import mysql.connector
def connect_to_db():
    return mysql.connector.connect(
        host="localhost",
        user="root",  # Change this
        password="Saipranith@2003",  # Change this
        database="heart_data")

In [47]:
# Features and target
X = df.drop(columns='heart disease')
y = df['heart disease']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train logistic regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

import joblib
joblib.dump(model,"log.pkl")

['log.pkl']

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score